import Head from 'next/head'
import IconPicker from '../components/IconPicker'
import { useState, useEffect } from 'react'

// ── Localhost-only guard ──────────────────────────────────────────────
// This page renders nothing on any deployed URL.
// It only works on localhost / 127.0.0.1.

function slug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
function uid() { return Math.random().toString(36).slice(2, 8) }

const MAT_TYPES = ['pdf', 'doc', 'link', 'video', 'other']

function emptyProgram()  { return { id:'', name:'', description:'', subjects:[] } }
function emptySubject()  { return { id:'', name:'', icon:'📘', description:'', coachIds:[], certificate:false, materials:[], topics:[] } }
function emptyTopic()    { return { id:'', name:'', description:'', coachIds:[], lessons:[] } }
function emptyLesson()   { return { id:'', title:'', videoId:'', duration:'', description:'', source:{ name:'', instructor:'', url:'' }, materials:[] } }
function emptyCoach()    { return { id:'', name:'', title:'', bio:'', avatar:null, signature:null, socials:{ youtube:'', website:'' } } }
function emptyMaterial() { return { id: uid(), label:'', url:'', type:'pdf' } }

// ── Code generator ────────────────────────────────────────────────────
function generateJS(coaches, programs) {
  const j = (v) => JSON.stringify(v)
  const matArr = (arr) => {
    if (!arr || arr.length === 0) return '[]'
    const items = arr.map(m => `{ id:${j(m.id)}, label:${j(m.label)}, url:${j(m.url)}, type:${j(m.type)} }`)
    return `[\n            ${items.join(',\n            ')}\n          ]`
  }
  const sourceStr = (s) => {
    if (!s || (!s.name && !s.instructor && !s.url)) return 'null'
    return `{ name:${j(s.name||'')}, instructor:${j(s.instructor||'')}, url:${j(s.url||'')} }`
  }
  const lessonStr = (l, pad) => `${pad}{
${pad}  id: ${j(l.id)},
${pad}  title: ${j(l.title)},
${pad}  videoId: ${j(l.videoId || 'YOUTUBE_ID_HERE')},
${pad}  duration: ${j(l.duration)},
${pad}  description: ${j(l.description)},
${pad}  source: ${sourceStr(l.source)},
${pad}  materials: ${matArr(l.materials)}
${pad}}`
  const topicStr = (t, pad) => `${pad}{
${pad}  id: ${j(t.id)},
${pad}  name: ${j(t.name)},
${pad}  description: ${j(t.description)},
${pad}  coachIds: ${j(t.coachIds||[])},
${pad}  lessons: [
${t.lessons.map(l=>lessonStr(l,pad+'    ')).join(',\n')}
${pad}  ]
${pad}}`
  const subjectStr = (s, pad) => `${pad}{
${pad}  id: ${j(s.id)},
${pad}  name: ${j(s.name)},
${pad}  icon: ${j(s.icon)},
${pad}  description: ${j(s.description)},
${pad}  coachIds: ${j(s.coachIds||[])},
${pad}  certificate: ${!!s.certificate},
${pad}  materials: ${matArr(s.materials)},
${pad}  topics: [
${s.topics.map(t=>topicStr(t,pad+'    ')).join(',\n')}
${pad}  ]
${pad}}`
  const programStr = (p, pad) => `${pad}{
${pad}  id: ${j(p.id)},
${pad}  name: ${j(p.name)},
${pad}  description: ${j(p.description)},
${pad}  subjects: [
${p.subjects.map(s=>subjectStr(s,pad+'    ')).join(',\n')}
${pad}  ]
${pad}}`

  const coachesJS = coaches.map(c => `  {
    id: ${j(c.id)},
    name: ${j(c.name)},
    title: ${j(c.title)},
    bio: ${j(c.bio)},
    avatar: ${c.avatar ? j(c.avatar) : 'null'},
    signature: ${c.signature ? j(c.signature) : 'null'},
    socials: { youtube: ${j(c.socials?.youtube||'')}, website: ${j(c.socials?.website||'')} }
  }`).join(',\n')

  return `// ============================================================
// FEYN, COURSE DATA
// Generated by Admin Panel, ${new Date().toISOString()}
// !! DO NOT add helpers here, they live in data/courseHelpers.js !!
// ============================================================

export const coaches = [
${coachesJS}
]

const data = {
  programs: [
${programs.map(p=>programStr(p,'    ')).join(',\n')}
  ]
}

export default data
`
}

// ── Main ──────────────────────────────────────────────────────────────
export default function AdminPage() {
  const [isLocal, setIsLocal]   = useState(false)
  const [checking, setChecking] = useState(true)

  const [coaches, setCoaches]   = useState([])
  const [programs, setPrograms] = useState([])

  const [selP, setSelP] = useState(null) // program idx
  const [selS, setSelS] = useState(null) // subject idx
  const [selT, setSelT] = useState(null) // topic idx
  const [selL, setSelL] = useState(null) // lesson idx

  const [modal, setModal]         = useState(null)
  const [modalData, setModalData] = useState({})
  const [editIdx, setEditIdx]     = useState(null)
  const [matTarget, setMatTarget] = useState(null) // {type:'subject'|'lesson'} for materials modal

  const [output, setOutput] = useState('')
  const [copied, setCopied] = useState(false)
  const [activeTab, setActiveTab] = useState('content') // 'content' | 'output'

  useEffect(() => {
    const h = window.location.hostname
    if (h === 'localhost' || h === '127.0.0.1' || h.startsWith('192.168.')) {
      setIsLocal(true)
      const saved = localStorage.getItem('ff_admin_data')
      if (saved) {
        try { const d = JSON.parse(saved); setCoaches(d.coaches||[]); setPrograms(d.programs||[]) } catch {}
      }
    }
    setChecking(false)
  }, [])

  useEffect(() => {
    if (!isLocal) return
    localStorage.setItem('ff_admin_data', JSON.stringify({ coaches, programs }))
  }, [coaches, programs, isLocal])

  if (checking) return null
  if (!isLocal) return <div style={{ display:'none' }} />

  // ── Derived ──
  const selProgram = selP !== null ? programs[selP] : null
  const selSubject = selProgram && selS !== null ? selProgram.subjects[selS] : null
  const selTopic   = selSubject && selT !== null ? selSubject.topics[selT] : null
  const selLesson  = selTopic && selL !== null ? selTopic.lessons[selL] : null

  // ── Mutators ──────────────────────────────────────────────
  function updatePrograms(fn) { setPrograms(p => fn([...p])) }

  function openModal(type, idx=null, extra=null) {
    setModal(type); setEditIdx(idx); setMatTarget(extra)
    if (idx !== null) {
      if (type==='program') setModalData({...programs[idx]})
      else if (type==='subject') setModalData({...selProgram.subjects[idx], coachIds:[...(selProgram.subjects[idx].coachIds||[])], materials:[...(selProgram.subjects[idx].materials||[])]})
      else if (type==='topic')   setModalData({...selSubject.topics[idx], coachIds:[...(selSubject.topics[idx].coachIds||[])]})
      else if (type==='lesson')  setModalData({...selTopic.lessons[idx], materials:[...(selTopic.lessons[idx].materials||[])], source:{...(selTopic.lessons[idx].source||{name:'',instructor:'',url:''})}})
      else if (type==='coach')   setModalData({...coaches[idx], socials:{...(coaches[idx].socials||{})}})
    } else {
      if (type==='program') setModalData(emptyProgram())
      else if (type==='subject') setModalData(emptySubject())
      else if (type==='topic')   setModalData(emptyTopic())
      else if (type==='lesson')  setModalData(emptyLesson())
      else if (type==='coach')   setModalData(emptyCoach())
    }
  }
  function closeModal() { setModal(null); setModalData({}); setEditIdx(null); setMatTarget(null) }

  function saveModal() {
    const d = { ...modalData }
    if (!d.id) d.id = slug(d.name || d.title || uid())
    const upsert = (arr) => editIdx !== null ? arr.map((x,i)=>i===editIdx?d:x) : [...arr, d]

    if (modal==='program') {
      setPrograms(upsert(programs))
    } else if (modal==='subject') {
      setPrograms(programs.map((p,i)=>i===selP ? {...p, subjects:upsert(p.subjects)} : p))
    } else if (modal==='topic') {
      setPrograms(programs.map((p,i)=>i!==selP?p:{...p,subjects:p.subjects.map((s,j)=>j!==selS?s:{...s,topics:upsert(s.topics)})}))
    } else if (modal==='lesson') {
      setPrograms(programs.map((p,i)=>i!==selP?p:{...p,subjects:p.subjects.map((s,j)=>j!==selS?s:{...s,topics:s.topics.map((t,k)=>k!==selT?t:{...t,lessons:upsert(t.lessons)})})}))
    } else if (modal==='coach') {
      setCoaches(upsert(coaches))
    }
    closeModal()
  }

  function del(type, idx) {
    if (!confirm('Delete this and all its children?')) return
    if (type==='program') { setPrograms(programs.filter((_,i)=>i!==idx)); setSelP(null);setSelS(null);setSelT(null);setSelL(null) }
    else if (type==='subject') { setPrograms(programs.map((p,i)=>i!==selP?p:{...p,subjects:p.subjects.filter((_,j)=>j!==idx)})); setSelS(null);setSelT(null);setSelL(null) }
    else if (type==='topic')   { setPrograms(programs.map((p,i)=>i!==selP?p:{...p,subjects:p.subjects.map((s,j)=>j!==selS?s:{...s,topics:s.topics.filter((_,k)=>k!==idx)})})); setSelT(null);setSelL(null) }
    else if (type==='lesson')  { setPrograms(programs.map((p,i)=>i!==selP?p:{...p,subjects:p.subjects.map((s,j)=>j!==selS?s:{...s,topics:s.topics.map((t,k)=>k!==selT?t:{...t,lessons:t.lessons.filter((_,m)=>m!==idx)})})})); setSelL(null) }
    else if (type==='coach')   { setCoaches(coaches.filter((_,i)=>i!==idx)) }
  }

  // ── Materials helpers (embedded in modal) ──
  function addMat() {
    setModalData(d => ({ ...d, materials: [...(d.materials||[]), emptyMaterial()] }))
  }
  function updateMat(i, field, val) {
    setModalData(d => {
      const mats = [...(d.materials||[])]
      mats[i] = { ...mats[i], [field]: val }
      return { ...d, materials: mats }
    })
  }
  function removeMat(i) {
    setModalData(d => ({ ...d, materials: (d.materials||[]).filter((_,j)=>j!==i) }))
  }

  function generate() {
    setOutput(generateJS(coaches, programs))
    setActiveTab('output')
  }
  function copy() { navigator.clipboard.writeText(output); setCopied(true); setTimeout(()=>setCopied(false),2000) }

  return (
    <>
      <Head><title>Admin · Feyn</title></Head>
      <div style={s.root}>

        {/* Header */}
        <div style={s.header}>
          <span style={s.logo}>Feyn, Admin <span style={{fontSize:11,color:'#5c5852',fontStyle:'normal'}}>localhost only</span></span>
          <div style={{display:'flex',gap:10,alignItems:'center'}}>
            <a href="/" target="_blank" style={s.btnGhost}>↗ View Site</a>
            <div style={{display:'flex',borderRadius:3,overflow:'hidden',border:'1px solid #2a2a2a'}}>
              {['content','output'].map(tab=>(
                <button key={tab} style={{...s.tabBtn, ...(activeTab===tab?s.tabBtnActive:{})}} onClick={()=>setActiveTab(tab)}>
                  {tab==='content' ? '⚙ Content' : '⬡ Export'}
                </button>
              ))}
            </div>
            <button style={s.btnAccent} onClick={generate}>Generate courses.js</button>
          </div>
        </div>

        {activeTab === 'content' && (
          <div style={s.body}>

            {/* Coaches panel */}
            <Panel title="Coaches" onAdd={()=>openModal('coach')}>
              {coaches.map((c,i)=>(
                <Row key={c.id} label={c.name} sub={c.title}
                  avatar={<Av>{c.name[0]||'?'}</Av>}
                  onEdit={()=>openModal('coach',i)} onDel={()=>del('coach',i)} />
              ))}
              {!coaches.length && <Empty>No coaches yet</Empty>}
            </Panel>

            {/* Programs */}
            <Panel title="Programs" onAdd={()=>openModal('program')}>
              {programs.map((p,i)=>(
                <Row key={p.id} label={p.name||'(unnamed)'} active={selP===i}
                  onClick={()=>{setSelP(i);setSelS(null);setSelT(null);setSelL(null)}}
                  onEdit={e=>{e.stopPropagation();openModal('program',i)}}
                  onDel={e=>{e.stopPropagation();del('program',i)}} />
              ))}
              {!programs.length && <Empty>No programs yet</Empty>}
            </Panel>

            {/* Subjects */}
            <Panel title={`Subjects${selProgram?`, ${selProgram.name}`:''}`} onAdd={selProgram?()=>openModal('subject'):null}>
              {!selProgram && <Empty>← Select a program</Empty>}
              {selProgram?.subjects.map((s2,i)=>(
                <Row key={s2.id} label={s2.name||'(unnamed)'} sub={s2.certificate?'🎓 cert':''} active={selS===i}
                  icon={<span style={{fontSize:16}}>{s2.icon}</span>}
                  onClick={()=>{setSelS(i);setSelT(null);setSelL(null)}}
                  onEdit={e=>{e.stopPropagation();openModal('subject',i)}}
                  onDel={e=>{e.stopPropagation();del('subject',i)}} />
              ))}
            </Panel>

            {/* Topics */}
            <Panel title={`Topics${selSubject?`, ${selSubject.name}`:''}`} onAdd={selSubject?()=>openModal('topic'):null}>
              {!selSubject && <Empty>← Select a subject</Empty>}
              {selSubject?.topics.map((t,i)=>(
                <Row key={t.id} label={t.name||'(unnamed)'} sub={`${t.lessons.length} lessons`} active={selT===i}
                  onClick={()=>{setSelT(i);setSelL(null)}}
                  onEdit={e=>{e.stopPropagation();openModal('topic',i)}}
                  onDel={e=>{e.stopPropagation();del('topic',i)}} />
              ))}
            </Panel>

            {/* Lessons, wider */}
            <Panel title={`Lessons${selTopic?`, ${selTopic.name}`:''}`} onAdd={selTopic?()=>openModal('lesson'):null} wide>
              {!selTopic && <Empty>← Select a topic</Empty>}
              {selTopic?.lessons.map((l,i)=>(
                <div key={l.id} style={{...s.row, ...(selL===i?s.rowActive:{})}} onClick={()=>setSelL(i)}>
                  <span style={s.rowNum}>{String(i+1).padStart(2,'0')}</span>
                  {l.videoId && l.videoId!=='YOUTUBE_ID_HERE' && (
                    <img src={`https://i.ytimg.com/vi/${l.videoId}/default.jpg`} crossOrigin="anonymous" alt="" style={{width:64,height:36,objectFit:'cover',borderRadius:2,flexShrink:0}} />
                  )}
                  <div style={{flex:1,minWidth:0}}>
                    <div style={s.rowLabel}>{l.title||'(untitled)'}</div>
                    <div style={s.rowSub}>
                      {l.videoId&&l.videoId!=='YOUTUBE_ID_HERE'
                        ? <span style={{color:'#c8a96e'}}>✓ {l.videoId}</span>
                        : <span style={{color:'#c0392b'}}>No video ID</span>}
                      {l.duration && <span> · {l.duration}</span>}
                      {l.materials?.length>0 && <span style={{color:'#5c5852'}}> · {l.materials.length} material{l.materials.length>1?'s':''}</span>}
                    </div>
                  </div>
                  <button style={s.iconBtn} onClick={e=>{e.stopPropagation();openModal('lesson',i)}}>✏️</button>
                  <button style={s.iconBtn} onClick={e=>{e.stopPropagation();del('lesson',i)}}>🗑</button>
                </div>
              ))}
            </Panel>

          </div>
        )}

        {activeTab === 'output' && (
          <div style={{padding:'0 0 40px'}}>
            {!output && (
              <div style={{padding:'60px 24px',textAlign:'center',color:'#5c5852'}}>
                <p style={{marginBottom:16}}>Click <strong style={{color:'#c8a96e'}}>Generate courses.js</strong> first</p>
                <button style={s.btnAccent} onClick={generate}>Generate now</button>
              </div>
            )}
            {output && (
              <>
                <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 24px',borderBottom:'1px solid #1e1e1e',background:'#0a0a0a',position:'sticky',top:57,zIndex:10}}>
                  <span style={{fontFamily:'monospace',fontSize:12,color:'#c8a96e'}}>data/index.js, copy this and save to your project</span>
                  <div style={{display:'flex',gap:8}}>
                    <button style={s.btnGhost} onClick={()=>{ const b=document.createElement('a');b.href='data:text/javascript,'+encodeURIComponent(output);b.download='courses.js';b.click() }}>⬇ Download</button>
                    <button style={s.btnAccent} onClick={copy}>{copied?'✓ Copied!':'Copy to clipboard'}</button>
                  </div>
                </div>
                <textarea style={s.outputCode} value={output} readOnly rows={32} spellCheck={false} />
                <p style={{padding:'10px 24px',color:'#5c5852',fontSize:11,fontFamily:'monospace'}}>
                  Paste into <code>data/index.js</code>, then: git add . && git commit -m "update courses" && git push
                </p>
              </>
            )}
          </div>
        )}

      </div>

      {/* ── MODAL ── */}
      {modal && (
        <div style={s.overlay} onClick={closeModal}>
          <div style={s.modalBox} onClick={e=>e.stopPropagation()}>
            <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:24}}>
              <h2 style={s.modalTitle}>{editIdx!==null?'Edit':'Add'} {modal.charAt(0).toUpperCase()+modal.slice(1)}</h2>
              <button style={{...s.iconBtn,fontSize:18}} onClick={closeModal}>✕</button>
            </div>

            {/* Program */}
            {modal==='program' && <>
              <F label="Name" value={modalData.name||''} onChange={v=>setModalData(d=>({...d,name:v,id:d.id||slug(v)}))} />
              <F label="ID (slug)" value={modalData.id||''} onChange={v=>setModalData(d=>({...d,id:v}))} mono />
              <F label="Description" value={modalData.description||''} onChange={v=>setModalData(d=>({...d,description:v}))} area />
            </>}

            {/* Subject */}
            {modal==='subject' && <>
              <F label="Name" value={modalData.name||''} onChange={v=>setModalData(d=>({...d,name:v,id:d.id||slug(v)}))} />
              <F label="ID (slug)" value={modalData.id||''} onChange={v=>setModalData(d=>({...d,id:v}))} mono />
              <IconPicker value={modalData.icon||''} onChange={v=>setModalData(d=>({...d,icon:v}))} />
              <F label="Description" value={modalData.description||''} onChange={v=>setModalData(d=>({...d,description:v}))} area />
              <CoachPicker coaches={coaches} selected={modalData.coachIds||[]} onChange={ids=>setModalData(d=>({...d,coachIds:ids}))} />
              <CheckField label="Enable certificate on completion" checked={!!modalData.certificate} onChange={v=>setModalData(d=>({...d,certificate:v}))} />
              <MaterialsEditor materials={modalData.materials||[]} onAdd={addMat} onUpdate={updateMat} onRemove={removeMat} label="Course Materials" />
            </>}

            {/* Topic */}
            {modal==='topic' && <>
              <F label="Name" value={modalData.name||''} onChange={v=>setModalData(d=>({...d,name:v,id:d.id||slug(v)}))} />
              <F label="ID (slug)" value={modalData.id||''} onChange={v=>setModalData(d=>({...d,id:v}))} mono />
              <F label="Description" value={modalData.description||''} onChange={v=>setModalData(d=>({...d,description:v}))} area />
              <CoachPicker coaches={coaches} selected={modalData.coachIds||[]} onChange={ids=>setModalData(d=>({...d,coachIds:ids}))} label="Coaches (overrides subject)" />
            </>}

            {/* Lesson */}
            {modal==='lesson' && <>
              <F label="Title" value={modalData.title||''} onChange={v=>setModalData(d=>({...d,title:v,id:d.id||slug(v)}))} />
              <F label="ID (slug)" value={modalData.id||''} onChange={v=>setModalData(d=>({...d,id:v}))} mono />
              <F label="YouTube Video ID" placeholder="e.g. dQw4w9WgXcQ" value={modalData.videoId||''} onChange={v=>setModalData(d=>({...d,videoId:v.trim()}))} mono hint="The part after ?v= in the YouTube URL" />
              <F label="Duration" placeholder="e.g. 12:30" value={modalData.duration||''} onChange={v=>setModalData(d=>({...d,duration:v}))} />
              <F label="Description" value={modalData.description||''} onChange={v=>setModalData(d=>({...d,description:v}))} area />
              <div style={{borderTop:'1px solid #2a2a2a',margin:'12px 0 8px',paddingTop:8}}>
                <label style={{fontFamily:'monospace',fontSize:'0.6rem',textTransform:'uppercase',letterSpacing:'0.1em',color:'#888',display:'block',marginBottom:8}}>Video Source Attribution</label>
                <F label="Platform name" placeholder="e.g. OnnoRokom Pathshala" value={(modalData.source||{}).name||''} onChange={v=>setModalData(d=>({...d,source:{...(d.source||{}),name:v}}))} />
                <F label="Instructor name" placeholder="e.g. Ratul Khan" value={(modalData.source||{}).instructor||''} onChange={v=>setModalData(d=>({...d,source:{...(d.source||{}),instructor:v}}))} />
                <F label="Channel / platform URL" placeholder="e.g. https://youtube.com/@..." value={(modalData.source||{}).url||''} onChange={v=>setModalData(d=>({...d,source:{...(d.source||{}),url:v}}))} mono />
              </div>
              {modalData.videoId && modalData.videoId!=='YOUTUBE_ID_HERE' && (
                <div style={{marginBottom:16}}>
                  <label style={s.fieldLabel}>Preview</label>
                  <div style={{position:'relative',paddingBottom:'56.25%',background:'#000',borderRadius:4,overflow:'hidden'}}>
                    <iframe src={`https://www.youtube.com/embed/${modalData.videoId}`} style={{position:'absolute',top:0,left:0,width:'100%',height:'100%',border:0}} allowFullScreen />
                  </div>
                </div>
              )}
              <MaterialsEditor materials={modalData.materials||[]} onAdd={addMat} onUpdate={updateMat} onRemove={removeMat} label="Lesson Materials" />
            </>}

            {/* Coach */}
            {modal==='coach' && <>
              <F label="Name" value={modalData.name||''} onChange={v=>setModalData(d=>({...d,name:v,id:d.id||slug(v)}))} />
              <F label="ID (slug)" value={modalData.id||''} onChange={v=>setModalData(d=>({...d,id:v}))} mono />
              <F label="Title / Role" placeholder="e.g. Lead Instructor" value={modalData.title||''} onChange={v=>setModalData(d=>({...d,title:v}))} />
              <F label="Bio" value={modalData.bio||''} onChange={v=>setModalData(d=>({...d,bio:v}))} area />
              <F label="Avatar image path" placeholder="/coaches/name.jpg" value={modalData.avatar||''} onChange={v=>setModalData(d=>({...d,avatar:v||null}))} mono />
              <F label="Signature image path" placeholder="/coaches/name-sig.png" value={modalData.signature||''} onChange={v=>setModalData(d=>({...d,signature:v||null}))} mono />
              <F label="Website URL" value={modalData.socials?.website||''} onChange={v=>setModalData(d=>({...d,socials:{...d.socials,website:v}}))} />
              <F label="YouTube URL" value={modalData.socials?.youtube||''} onChange={v=>setModalData(d=>({...d,socials:{...d.socials,youtube:v}}))} />
            </>}

            <div style={{display:'flex',gap:10,justifyContent:'flex-end',marginTop:12,paddingTop:16,borderTop:'1px solid #2a2a2a'}}>
              <button style={s.btnGhost} onClick={closeModal}>Cancel</button>
              <button style={s.btnAccent} onClick={saveModal}>{editIdx!==null?'Save changes':'Add'}</button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}

// ── Sub-components ────────────────────────────────────────────────────
function Panel({ title, onAdd, wide, children }) {
  return (
    <div style={{...s.panel, ...(wide?{flex:2}:{})}}>
      <div style={s.panelHeader}>
        <span style={s.panelTitle}>{title}</span>
        {onAdd && <button style={s.addBtn} onClick={onAdd}>+ Add</button>}
      </div>
      <div style={{overflowY:'auto',flex:1}}>{children}</div>
    </div>
  )
}

function Row({ label, sub, icon, avatar, active, onClick, onEdit, onDel }) {
  return (
    <div style={{...s.row,...(active?s.rowActive:{}),...(onClick?{cursor:'pointer'}:{})}} onClick={onClick}>
      {avatar || (icon ? <span style={{marginRight:6,flexShrink:0}}>{icon}</span> : null)}
      <div style={{flex:1,minWidth:0}}>
        <div style={s.rowLabel}>{label}</div>
        {sub && <div style={s.rowSub}>{sub}</div>}
      </div>
      {onEdit && <button style={s.iconBtn} onClick={onEdit}>✏️</button>}
      {onDel && <button style={s.iconBtn} onClick={onDel}>🗑</button>}
    </div>
  )
}

function Av({ children }) {
  return <span style={{width:26,height:26,borderRadius:'50%',background:'#2a2a2a',display:'inline-flex',alignItems:'center',justifyContent:'center',fontSize:12,color:'#c8a96e',flexShrink:0,marginRight:8}}>{children}</span>
}

function Empty({ children }) {
  return <p style={{padding:'14px 16px',fontSize:12,color:'#5c5852',fontStyle:'italic'}}>{children}</p>
}

function F({ label, value, onChange, area, mono, placeholder, hint }) {
  return (
    <div style={{marginBottom:13}}>
      <label style={s.fieldLabel}>{label}</label>
      {area
        ? <textarea style={{...s.input,minHeight:72,resize:'vertical'}} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} />
        : <input style={{...s.input,fontFamily:mono?'monospace':undefined}} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} />}
      {hint && <p style={{fontSize:11,color:'#5c5852',marginTop:3}}>{hint}</p>}
    </div>
  )
}

function CheckField({ label, checked, onChange }) {
  return (
    <label style={{display:'flex',alignItems:'center',gap:8,marginBottom:14,color:'#9a9488',fontSize:13,cursor:'pointer'}}>
      <input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} />
      {label}
    </label>
  )
}

function CoachPicker({ coaches, selected, onChange, label='Coaches' }) {
  if (!coaches.length) return null
  return (
    <div style={{marginBottom:14}}>
      <label style={s.fieldLabel}>{label}</label>
      <div style={{display:'flex',flexWrap:'wrap',gap:8}}>
        {coaches.map(c=>(
          <label key={c.id} style={{display:'flex',alignItems:'center',gap:5,cursor:'pointer',color:'#9a9488',fontSize:13}}>
            <input type="checkbox" checked={selected.includes(c.id)}
              onChange={e=>onChange(e.target.checked ? [...selected,c.id] : selected.filter(x=>x!==c.id))} />
            {c.name}
          </label>
        ))}
      </div>
    </div>
  )
}

function MaterialsEditor({ materials, onAdd, onUpdate, onRemove, label }) {
  return (
    <div style={{marginBottom:14}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:8}}>
        <label style={s.fieldLabel}>{label} ({materials.length})</label>
        <button style={{...s.addBtn,padding:'3px 10px'}} onClick={onAdd}>+ Add material</button>
      </div>
      {materials.map((m,i)=>(
        <div key={m.id} style={{display:'flex',gap:6,marginBottom:6,alignItems:'flex-start'}}>
          <input style={{...s.input,flex:2,fontSize:12}} placeholder="Label" value={m.label} onChange={e=>onUpdate(i,'label',e.target.value)} />
          <input style={{...s.input,flex:3,fontSize:12,fontFamily:'monospace'}} placeholder="URL" value={m.url} onChange={e=>onUpdate(i,'url',e.target.value)} />
          <select style={{...s.input,flex:1,fontSize:12}} value={m.type} onChange={e=>onUpdate(i,'type',e.target.value)}>
            {MAT_TYPES.map(t=><option key={t} value={t}>{t}</option>)}
          </select>
          <button style={{...s.iconBtn,marginTop:2}} onClick={()=>onRemove(i)}>🗑</button>
        </div>
      ))}
      {!materials.length && <p style={{fontSize:11,color:'#5c5852',fontStyle:'italic'}}>No materials yet</p>}
    </div>
  )
}

// ── Inline styles ─────────────────────────────────────────────────────
const s = {
  root:   { minHeight:'100vh', background:'#0d0d0d', color:'#e8e3d8', fontFamily:"'DM Sans',sans-serif", display:'flex', flexDirection:'column' },
  header: { display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 20px', height:57, borderBottom:'1px solid #1e1e1e', position:'sticky', top:0, background:'rgba(13,13,13,0.98)', zIndex:50, backdropFilter:'blur(10px)', flexShrink:0 },
  logo:   { fontFamily:"Georgia,serif", fontSize:15, letterSpacing:'0.01em' },
  body:   { display:'flex', flex:1, overflow:'hidden' },
  panel:  { flex:1, minWidth:180, borderRight:'1px solid #1a1a1a', display:'flex', flexDirection:'column', height:'calc(100vh - 57px)', overflow:'hidden' },
  panelHeader: { display:'flex', alignItems:'center', justifyContent:'space-between', padding:'10px 14px', borderBottom:'1px solid #1a1a1a', flexShrink:0 },
  panelTitle: { fontFamily:'monospace', fontSize:10, letterSpacing:'0.1em', textTransform:'uppercase', color:'#5c5852' },
  addBtn: { background:'none', border:'1px solid #2a2a2a', color:'#c8a96e', fontSize:11, padding:'3px 9px', cursor:'pointer', borderRadius:2, fontFamily:'monospace' },
  row:    { display:'flex', alignItems:'center', padding:'8px 14px', gap:8, borderBottom:'1px solid #111', minHeight:44, transition:'background 120ms' },
  rowActive: { background:'#1a1a1a', borderLeft:'2px solid #c8a96e' },
  rowLabel: { fontSize:13, color:'#e8e3d8', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' },
  rowSub:   { fontSize:10, color:'#5c5852', fontFamily:'monospace', marginTop:1 },
  rowNum:   { fontFamily:'monospace', fontSize:11, color:'#5c5852', minWidth:22 },
  iconBtn:  { background:'none', border:'none', cursor:'pointer', fontSize:12, opacity:0.5, padding:'2px 3px', flexShrink:0 },
  tabBtn:   { background:'none', border:'none', padding:'6px 14px', fontSize:12, color:'#5c5852', cursor:'pointer', fontFamily:'monospace', letterSpacing:'0.06em' },
  tabBtnActive: { background:'#1a1a1a', color:'#c8a96e' },
  outputCode: { width:'100%', background:'#090909', color:'#9a9488', fontFamily:'monospace', fontSize:12, padding:'16px 24px', border:'none', outline:'none', resize:'vertical', lineHeight:1.55, display:'block' },
  overlay:  { position:'fixed', inset:0, background:'rgba(0,0,0,0.82)', zIndex:300, display:'flex', alignItems:'center', justifyContent:'center', padding:20 },
  modalBox: { background:'#141414', border:'1px solid #2a2a2a', borderRadius:4, padding:'24px 28px', width:'100%', maxWidth:560, maxHeight:'92vh', overflowY:'auto' },
  modalTitle: { fontFamily:"Georgia,serif", fontSize:17, color:'#e8e3d8' },
  fieldLabel: { display:'block', fontFamily:'monospace', fontSize:10, letterSpacing:'0.1em', textTransform:'uppercase', color:'#5c5852', marginBottom:5 },
  input: { display:'block', width:'100%', background:'#0d0d0d', border:'1px solid #2a2a2a', color:'#e8e3d8', padding:'7px 10px', fontSize:13, borderRadius:2, outline:'none', fontFamily:'inherit', boxSizing:'border-box' },
  btnAccent: { background:'#1a1308', border:'1px solid #8b6f3e', color:'#c8a96e', padding:'7px 18px', cursor:'pointer', fontSize:13, borderRadius:2, fontFamily:'inherit' },
  btnGhost:  { background:'none', border:'1px solid #2a2a2a', color:'#9a9488', padding:'7px 18px', cursor:'pointer', fontSize:13, borderRadius:2, fontFamily:'inherit' },
}
